# Change these first
owner: soramitsukhmer # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Fast Development
    url: https://web-fast-dev.sorakh.app/
  - name: Fast Integration
    url: https://web-fast-integration.sorakh.app/
  - name: NCS Development
    url: https://web-ncs-dev.sorakh.app/
  - name: NCS Integration
    url: https://web-ncs-integration.sorakh.app/

status-website:
  apiBaseUrl: https://api.github.com
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.soramitsukhmer.com
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/soramitsukhmer/upptime/master/assets/soramitsukhmer-upptime-icon.svg
  name: Upptime — Soramitsu Khmer
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
